version: '3.9'

services:
  yf-wrapper:
    build:
      context: https://github.com/jhigatzberger/yf-rest_wrapper.git
      dockerfile: Dockerfile
    container_name: yf-wrapper
    ports:
      - "5000:5000"
    restart: unless-stopped
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dashboard
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - yf-wrapper
